### PR TITLE
README.md - Fix spelling

### PR DESCRIPTION
**Pull request by sehnpaa**

### CODE REVIEW

**Comment by kbknapp** [comment]
Thanks! :+1:

@homu r+

**Comment by kbknapp** [comment]
Hmmn looks like clippy is failing. Actually I need to pull that one out
anyways because it requires a dylib external...once I get to a computer
I'll comment out clippy from the readme and cargo.toml and merge this.

**Comment by kbknapp** [comment]
Now that #14 has merged, can you rebase onto master (and you might as well include #12 as well :wink:) and this will be read for a merge!

**Comment by sehnpaa** [comment]
Sorry about the delay. I didn't quite manage to get the rebasing and squashing to succeed. Going to have to re-evaluate my awesome git skill I guess... ;-)
Thanks for helping out!

**Pull request merged**
